### ISSUE TITLE
Default shapes (no GeometryDash.exe)

### ISSUE THREAD

**Issue by Anonymous3-a** [gstaaij/geometryfoss#1]
I don't have GeometryDash.exe (partially because I use GNU/Linux, partially because I don't use Steam anymore). I compiled the executable, and it says "Drag GeometryDash.exe to this window or click here to locate it".
<details><summary>Image of window</summary>
<img src="https://github.com/gstaaij/geometryfoss/assets/74880413/72144c06-a5a9-40bf-b4c0-16d3612a877f">
</details>

THEPLAN.md says:
```
If someone doesn't have Geometry Dash, they will see default shapes for the objects with a hitbox, and they will not be able to see any of the decorations.
```

I am using Tails OS (which is based on Debian).

If I click, it doesn't do anything. I clicked buttons to see if anything would happen, but only F3 worked (but only hiding the TPS/FPS as it said). Got a way to use default shapes? I'll see if I can edit the code to get it to use default shapes.

**Comment by gstaaij** [comment]
Thank you for your interest!

I'm currently developing the texture copying system, and I haven't implemented anything to skip that screen yet. I'll add it as soon as possible.

I will add some text to the readme so it's more clear that, because this project is in development, some things that are currently being worked on are not expected to fully work yet.
